image: node:16.13.2

stages:
  - publish

publish:
  stage: publish
  tags:
    - docker-build
  script:
    - npm install
    - npm run build-GT
    - npm run build-Qua
    - npm run build-Ele
    - sed 's/"version"':' .*/"version":\ "'${CI_COMMIT_TAG}'",/g' ./package.json
    - echo "//prg.greattree.com.tw/repository/npm-gt/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - echo "registry=${REGISTRY_URL}" >> ~/.npmrc
    - npm publish
  only:
    - tags

