image: node:16.13.2

stages:
  - publish

publish:
  stage: publish
  tags:
    - docker-build
  script:
    - npm install
    - npm run build-GT
    - npm run build-Qua
    - npm run build-Ele
    - echo "//prg.greattree.com.tw/repository/npm-gt/:_authToken=$npmtoken" > ~/.npmrc
    - echo "registry=$registryurl" >> ~/.npmrc
    - npm publish
  only:
    - feature
