image: node:16.13.2

stages:
  - publish
  - build-page

publish:
  stage: publish
  tags:
    - docker-build
  script:
    - npm install
    - npm run build-GT
    - npm run build-Qua
    - npm run build-Ele
    - sed -i 's/"version":\ .*/"version":\ "'${CI_COMMIT_TAG}'",/g' ./package.json
    - echo "//prg.greattree.com.tw/repository/npm-gt/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - echo "registry=${REGISTRY_URL}" >> ~/.npmrc
    - npm publish
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}
    paths:
      - dist
  only:
    - tags

pages:
  stage: build-page
  tags:
    - docker-build
  script:
    - sed -i "s/config.base = .*/config.base = '\/${CI_PROJECT_NAME}\/'/g" ./vite.config.js
    - npm install
    - npm run build-GT
    - npm run build-Qua
    - npm run build-Ele
    - npm run build-demo
    - cp -a demo/* public/
    - cp public/index.html public/404.html
  artifacts:
    name: page-${CI_PROJECT_NAME}-${CI_COMMIT_TAG}
    paths:
      - public
  only:
    - tags