/* eslint-disable */

/** 
 * !--------- FBI WARNING ----------!
 * 
 * 根据 /packages 目录下的组件所生成的模块导出，请勿手动修改
 */

export default {
    'avatar': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| imgUrl | String |  | | |\n| size | String |  | md | md |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'button': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| width | 寬度 | Number | | |\n| type | 類型 | String | second、green、yellow、red、black、white  | second |\n| pill | 膠囊型 | Boolean | | |\n| flat | 文字型 | Boolean | | |\n| noBorder | 無框型 | Boolean | | |\n| icon | 圖示 | String | 參照icon項目 | |\n| iconPosition | 圖示位置 | String | left、right | left |\n| isLoading | 載入中 | Boolean | | |\n| iconClasses | 自定義icon樣式 | String | | |\n| flatHover | flat樣式中，是否顯示hover底線 | Boolean | | true |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'checkbox': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 狀態值 | Boolean | | false |\n| label | 標籤 | String | | |\n| disabled | 禁用 | Boolean | | false |\n| **群組勾選使用**|\n| v-model | 狀態值 | Array[Value(Any)] | | |\n| value | 選項 | Any | |  |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'collapse-card': {"show":["prop","slot"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| isOpen | 是否為展開 | Boolean | | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| title | 標題區塊 |\n| content | 內容區塊 |\n\n"}, 
    'collapse-card-section': {}, 
    'dialog': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 顯示 | Boolean | | false |\n| title | 標題 | String | | |\n| mode | 對話窗模式 | String | comfirm、delete | comfirm |\n| size | 對話窗尺寸 | String | sm、md、lg | sm |\n| align | 對齊位置 | String | left、center、right | left |\n| handleCallback | 自訂確認動作後回call事件 | Function | | ()=>{} |\n| width | 自定義對話窗寬度 | Number |  |  |\n| height | 自定義對話窗高度 | Number |  |  |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | |  |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'divider': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| horizontal | 水平分割線 | Boolean | | true |\n| vertical | 垂直分割線。會吃結構中的父層高度。 | Boolean | | false |\n| height | vertical模式中，分割線佔父層高度的佔比  | String | | 100% |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | |  |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'download-icon': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| percent | 百分比 | Number | | 0 |\n| auto | 自動轉動 | Boolean | | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'dropdown': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 選項數據 | Object{ItemName:ItemValue} |  |  |\n| options | 選項 | Array[Option{label(String),value(Any)}] |  |  |\n| clicked | 點擊模式 | Boolean |  | true |\n| icon | 是否顯示選項圖示 | Boolean |  | false |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| - | - | - |\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n|  |  |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'dropdownitem': {"show":["prop","event"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| label | String |  |  |  |\n| value | Any |  |  |  |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| - | - | - |\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| itemClick | 綁定click，回傳當前label,value |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'filter-chips': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 選項值 | Boolean | | false |\n| label | 選項名稱 | Array[OptionObject{label(String),value(Any)}] | | |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n|  |  | |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'filter-chips-group': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 選項值 | Boolean | | false |\n| optionName | 選項名稱 | Array[OptionObject{label(String),value(Any)}] | | |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n|  |  | |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'form': {"show":["prop","method"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| name | 表單名稱 | String |  |  |\n| v-model | 表單數據 | Object{ItemName:ItemValue} |  |  |\n| rules | 驗證規則 | Object{ItemName:Rules(Array)} |  |  |\n|  |  | Rules(Array):[{require?:Boolean,message:String,trigger?:EventType(String)}] |  |  |\n|  |  | EventType(String):'blur' |  |  |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\ncallValid | 使用form的名稱註冊於全局屬性中。例如name是form1，globalProperties['gForms-form1']會有此方法<br>或以instance.refs方式使用| |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n|  |  |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'icon': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| name | 圖示名 | String | | |\n| size | 尺寸 | String | sm、md、lg  | md |\n| classes | 自定義classes | String |   |  |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'img-upload': {"show":["method"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| | | | |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| file | 載入檔案後觸發，回傳File |  |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'input': {"show":["prop","method","event"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| type | 類型 | InputType(String) | text、number、password | text |\n| v-model | 狀態值 | any |  |  |\n| placeholder | 預設提示字 | String |  |  |\n| label | 標題 | String | | |\n| width | 寬度 | Number | | |\n| size | 大小(高度) | SizeType(String) | sm、md | sm |\n| green | 大樹綠 | Boolean | | false |\n| icon | 圖示 | IconType(String) | 參考圖示頁 | |\n| disabled | 禁用 | Boolean | | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| focusInput | 使input進入focus狀態。透過ref綁定後使用該方法，如instance.refs.inputA.focusInput() |  \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| blur | 觸發blur事件後回傳 |\n| focus | 觸發focus事件後回傳 | \n| keyup | 觸發keyup事件後回傳 | \n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'input-number': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 狀態值 | Number |  | |\n| max | 最大值 | Number |  |  |\n| min | 最小值 | Number |  | 0 |\n| 操作單位 | 最小值 | Number |  | 1 |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'layout': {"show":["prop","event","slot"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| headText | 左上標題 | String | | |\n| title | 頁面標題 | String | | |\n| menuTabs | 選單頁籤 | Array[Item{name(String),path(String)}] | | |\n| collapsed | sidebar區塊收開狀態。收:寬80px，開:寬300px。 | Boolean | | false |\n| onlyOneLevel | menu只有一層的模式 | Boolean | | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| collapsed | 接收collapsed變動的回傳 | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| header | 以flex justify-between排版，插槽內容向右對齊 | \n| content | 主內容區塊 | \n\n"}, 
    'loading': {"show":["method"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| | | | | |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| handleLoadingTrigger | 呼叫頁面載入效果 | |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'loading-icon': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| 無 | |  | | |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'menu': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| active | 當前路由，格式範例 \"2-1\"，即對應menu第二項的第一個children | String | | |\n| activePath | 當前路由，格式範例 \"/gt/menu\"，即對應menu中相同path | String | | |\n| menu | Vue Router 路由樹狀物件。 | Array[MenuItem] <br> MenuItem : {label:String,path?:String,children?:{label:String,icon?:IconType(String) <br> ,iconClasses?:String,path:String},icon?:IconType(String),iconClasses?:String} | | |\n| collapsed | 收開狀態。可綁ref後訪問，如instance.refs.menuRef.collapsed來變更狀態 | Boolean | | false |\n| onlyOneLevel | menu只有一層的模式 | Boolean | | false |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n|  |  | \n\n"}, 
    'message': {"show":["method"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| | | | | |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| handleMessageTrigger | 呼叫通知 | { msg:String , type:'info'(default)、'warning'、'error'  } , title:String } |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'message-toast': {"show":["prop","method"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| text | 通知文字 | String | | 儲存成功! |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| handleMessageToastTrigger | 呼叫通知 | time:Number (default 1200) 毫秒 |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'option': {}, 
    'pagination': {"show":["prop","event"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| pageInfo | 頁籤資料 | Object{currentPage(Number),total(Number),perPageNums(Number)} | | |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| handleMessageToastTrigger | 呼叫通知 | time:Number (default 1200) 毫秒 |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| updatePage | 回傳currentPage| |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'radiobox': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 狀態值 | Boolean | | false |\n| label | 標籤 | String | | |\n| disabled | 禁用 | Boolean | | false |\n| **群組單選使用**|\n| v-model | 狀態值 | Any | | |\n| value | 選項 | Any | |  |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'select': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| bindResult | 回傳值地綁定模式  | String | index,value,label | index |\n| multiple | 多選模式  | Boolean | | false |\n| v-model | 單選模式、綁定index時<br>單選模式、綁定value時<br/>單選模式、綁定label時 | index<br/>value<br/>label | | |\n| v-model | 多選模式、綁定index時<br>多選模式、綁定value時<br/>多選模式、綁定label時  | [index]<br/>[value]<br/>[label] | | |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'sort-label': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 標籤值 | String | | |\n| options | 標籤選項 | Array[OptionObject{label(String),value(Any)}] | | |\n| labelName | 排序標籤名 | String | | |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| handleMessageToastTrigger | 呼叫通知 | time:Number (default 1200) 毫秒 |\n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'switch': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 狀態值 | Boolean | | false |\n| statusLabel | 狀態標籤 | Boolean | | false |\n\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'table': {"show":["prop","method","slot"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| name | 表名稱。 | String |  |  |\n| columns | 欄位 | Array[ColumnObject{Column(String),label(String),<br>width(Number),sort(Boolean),handleSortCallback(function) }] |  |  |\n| data | 資料 | Array[RowObject{ Column:DataCell(Any) }] |  |  |\n| isCheckBox | 顯示勾選欄 | Boolean |  | true |\n| width | 表高度。超過寬度則有X捲軸 | Number |  |  |\n| height | 表高度。超過高度則有Y捲軸 | Number |  |  |\n| rowClick | 點選row即可勾選 | Boolean |  | false |\n| isLoading | 顯示載入效果 | Boolean |  | false |\n| underline | row底線 | Boolean |  | false |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| getCheckedList | 呼叫勾選清單。使用table的名稱註冊於全局屬性中。,<br>例如name是product，globalProperties['gt-table-product']會有此方法<br>或以instance.refs方式使用 | |\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n|  |  |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| v-slot:**Column**=\"{ row }\" | 使用Column作為插槽名稱，row即為該筆資料的Object| \n\n"}, 
    'table-column': {}, 
    'table2': {"show":["prop","method","slot"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| name | 表名稱。 | String |  |  |\n| columns | 欄位 | Array[ColumnObject{Column(String),label(String),<br>width(Number),sort(Boolean),handleSortCallback(function) }] |  |  |\n| data | 資料 | Array[RowObject{ Column:DataCell(Any) }] |  |  |\n| isCheckBox | 顯示勾選欄 | Boolean |  | true |\n| width | 表高度。超過寬度則有X捲軸 | Number |  |  |\n| height | 表高度。超過高度則有Y捲軸 | Number |  |  |\n| rowClick | 點選row即可勾選 | Boolean |  | false |\n| isLoading | 顯示載入效果 | Boolean |  | false |\n| underline | row底線 | Boolean |  | false |\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| getCheckedList | 呼叫勾選清單。使用table的名稱註冊於全局屬性中。,<br>例如name是product，globalProperties['gt-table-product']會有此方法<br>或以instance.refs方式使用 | |\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n|  |  |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| v-slot:**Column**=\"{ row }\" | 使用Column作為插槽名稱，row即為該筆資料的Object| \n\n"}, 
    'tabs': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| tabs | 頁籤 | Array[Tab{name:String}] | | |\n| currentTab | 當前頁籤 | String | | |\n| clickCallback | 回傳點擊的Tab Object | Function | | |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'tag': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| label | 狀態值 | String | | |\n| type | 樣式類型 | String | DEFAULT、SECOND、DANGER、WARNING、ACTIVITY | DEFAULT |\n| border | 邊框 | Boolean | | false |\n| dot | 圓點圖示 | Boolean | | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'time-picker': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| v-model | 時間 | String |  |  |\n| format | 格式。參考dayjs format | String |  | YYYY-MM-DD HH:mm |\n| width | 寬度 | Number |  | 180 |\n| autoHideLabel | 標籤選取後隱藏 | Boolean |  | true |\n| rangeSelectMode | 日期範圍選擇模式 | Boolean |  | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| - | - | - |\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n|  |  |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'timeline': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| isEnd | 是否顯示為最後的樣式 | Boolean |  |  |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| - | - | - |\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n|  |  |  |\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'timelineitem': {}, 
    'title': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| level | 級距 | Number | 0、1、2、3 | 0 |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'tooltip': {"show":["prop","slot"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| position | 提示位置 | String | right、left、top、bottom | right |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| content | 提示內容 | \n\n"}, 
    'tree': {"show":["prop","expose"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| data | tree結構資料 |Array[TreeItem] ; <br/> TreeItem:Object{label:String,value:Boolean,children?:Array[TreeItem],clickCallBack?:Function,disabled?:Boolean} |  |  |\n\n","expose":"\n## 暴露\n| 名稱 | 說明 | 參數 |\n| - | - | - |\n| data | 當前的樹狀資料 | \n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'upload-icon': {"show":["prop"],"prop":"\n## 屬性\n| 屬性 | 說明 | 類型 | 可選值 | 默認值 |\n| - | - | - |- | -  |\n| percent | 百分比 | Number | | 0 |\n| auto | 自動轉動 | Boolean | | false |\n\n","method":"\n## 方法\n| 方法 | 說明 | 參數 |\n| - | - | - |\n| | | \n\n","event":"\n## 事件\n| 事件 | 說明 | 參數 |\n| - | - | - |\n| | | |\n\n","slot":"\n## 插槽\n| 插槽 | 說明 | \n| - | - | \n| | | \n\n"}, 
    'pagination2': {}, 
};

